python execute_enhancers_runx1_1.py
python execute_enhancers_runx1_2.py
python execute_enhancers_runx1_3.py

python execute_enhnacers_ets1.py

python execute_enhancers_hoxb13_1.py
python execute_enhancers_hoxb13_2.py

python execute_enhancers_pou6f1.py

python execute_enhnacers_foxo3a_1.py
python execute_enhancers_foxo3a_2.py

python execute_enhancers_klf3.py

python execute_enhancers_irf1.py

python execute_enhancers_creb1_1.py
python execute_enhancers_creb1_2.py

python execute_enhancers_egr1_1.py
python execute_enhancers_egr1_2.py

python execute_enhancers_stat1_1.py
python execute_enhancers_stat1_2.py

python execute_enhancers_mitf_1.py
python execute_enhancers_mitf_2.py

python execute_enhancers_gzf1.py